services:
    php:
        container_name: ${COMPOSE_PROJECT_NAME}-php
        build:
            target: frankenphp
        volumes:
            - build:/app/public/build
            - node_modules:/app/node_modules
            - var:/app/var
            - vendor:/app/vendor
            - .:/app
        ports:
            - 80:80
            - 443:443
            - 443:443/udp
        environment:
            CADDY_GLOBAL_OPTIONS: debug
            SERVER_NAME: ${SERVER_NAME:-localhost}
        restart: unless-stopped

volumes:
    build:
    node_modules:
    var:
    vendor:
